# Gradle 7.0 부터 Version Catalog 를 지원한다.
[versions]
# App Version
app-versioncode = "1"
app-versionname = "0.0.1"
# SDK Version
sdk-min = "24"
sdk-target = "33"
sdk-compile = "33"
# Plugin Version
plugin-gradle = "8.2.1"
# Kotlin
kotlin = "1.9.21"
ksp = "1.9.21-1.0.16"
coroutines = "1.7.3"
# Hilt
hilt = "2.47"
# AndroidX
androidx-core = "1.12.0"
androidx-navigation = "2.7.6"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-fragment = "1.6.2"
androidx-lifecycle = "2.6.2"
androidx-room = "2.6.1"
# Google
google-material = "1.11.0"
# Network
retrofit = "2.9.0"
retrofit-coroutines-adapter = "0.9.2"
kotlinx-serialization = "1.6.1"
kotlinx-serialization-converter = "0.8.0"
# UI
glide = "4.14.2"
lottie = "5.2.0"
shimmer = "0.5.0"
rds = "0.3.0"
# Debug
flipper = "0.177.0"
flipper-soloader = "0.10.4"
leakcanary = "2.12"
# Common
timber = "5.0.1"
ted-permission = "3.3.0"

[libraries]
# Kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
# AndroidX Presentation
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
# AndroidX Data
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-coroutine = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
# Google
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
# Network
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-coroutines-adapter = { module = "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter", version.ref = "retrofit-coroutines-adapter" }
retrofit-scalars-converter = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization-converter" }
# UI
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
ted-permission = { module = "io.github.ParkSangGwon:tedpermission-coroutine", version.ref = "ted-permission" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
rds = { module = "com.github.ajou4095:Ray-Design-System", version.ref = "rds" }
# Flipper
flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
flipper-network = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "flipper" }
flipper-leakcanary = { module = "com.facebook.flipper:flipper-leakcanary2-plugin", version.ref = "flipper" }
flipper-soloader = { module = "com.facebook.soloader:soloader", version.ref = "flipper-soloader" }
# Common
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-gradle" }
android-library = { id = "com.android.library", version.ref = "plugin-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "androidx-navigation" }

[bundles]
kotlin = ["kotlin", "kotlinx-coroutines-android", "kotlinx-coroutines-core"]
androidx-presentation = ["androidx-core", "androidx-appcompat", "androidx-constraintlayout", "androidx-fragment",
    "androidx-viewmodel", "androidx-livedata", "androidx-navigation-fragment", "androidx-navigation-ui"]
androidx-data = ["androidx-room-runtime", "androidx-room-coroutine"]
network = ["retrofit", "retrofit-coroutines-adapter", "retrofit-scalars-converter", "kotlinx-serialization", "kotlinx-serialization-converter"]
flipper = ["flipper", "flipper-network", "flipper-leakcanary", "flipper-soloader"]
