# Gradle 7.0 부터 Version Catalog 를 지원한다.
[versions]
# App Version
app-versioncode = "1"
app-versionname = "0.0.1"
# SDK Version
sdk-min = "24"
sdk-target = "34"
sdk-compile = "34"
# Plugin Version
plugin-gradle = "8.2.1"
plugin-sentry = "4.1.1"
# Kotlin
kotlin = "1.9.21"
ksp = "1.9.21-1.0.16"
coroutines = "1.7.3"
kotlinx-datetime = "0.5.0"
# Hilt
hilt = "2.47"
# AndroidX
androidx-core = "1.12.0"
androidx-navigation = "2.7.6"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-fragment = "1.6.2"
androidx-lifecycle = "2.6.2"
androidx-room = "2.6.1"
androidx-paging = "3.1.1"
# Google
google-material = "1.11.0"
# Network
ktor = "2.3.7"
kotlinx-serialization = "1.6.1"
# UI
glide = "4.14.2"
lottie = "5.2.0"
shimmer = "0.5.0"
rds = "0.3.0"
# Logging
timber = "5.0.1"
sentry = "7.1.0"
# Debug
leakcanary = "2.12"
okhttp3-logging-interceptor = "4.9.1"
# Common
ted-permission = "3.3.0"

[libraries]
# Kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
# AndroidX Presentation
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
# AndroidX Data
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-coroutine = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }
androidx-paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "androidx-paging" }
# Google
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
# Network
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-kotlinx-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
# UI
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
ted-permission = { module = "io.github.ParkSangGwon:tedpermission-coroutine", version.ref = "ted-permission" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
rds = { module = "com.github.ajou4095:Ray-Design-System", version.ref = "rds" }
# Logging
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
sentry = { module = "io.sentry:sentry-android", version.ref = "sentry" }
# Debug
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3-logging-interceptor" }

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-gradle" }
android-library = { id = "com.android.library", version.ref = "plugin-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "androidx-navigation" }
sentry = { id = "io.sentry.android.gradle", version.ref = "plugin-sentry" }

[bundles]
kotlin = ["kotlin", "kotlinx-coroutines-android", "kotlinx-coroutines-core", "kotlinx-datetime"]
androidx-presentation = ["androidx-core", "androidx-appcompat", "androidx-constraintlayout", "androidx-fragment",
    "androidx-viewmodel", "androidx-livedata", "androidx-navigation-fragment", "androidx-navigation-ui"]
androidx-data = ["androidx-room-runtime", "androidx-room-coroutine", "androidx-paging-runtime"]
network = ["ktor-core", "ktor-okhttp", "ktor-resources", "ktor-content-negotiation", "ktor-kotlinx-serialization",
    "ktor-auth", "kotlinx-serialization"]
logging = ["timber", "sentry"]
