# Gradle 7.0 부터 Version Catalog 를 지원한다.
[versions]
# App Version
app-versioncode = "1"
app-versionname = "0.0.1"
# SDK Version
sdk-min = "24"
sdk-target = "34"
sdk-compile = "34"
# Plugin Version
plugin-gradle = "8.2.2"
plugin-sentry = "4.1.1"
plugin-gms = "4.4.1"
plugin-firebase-crashlytics = "2.9.9"
# Kotlin
# TODO : Kotlin 2.0.0
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"
coroutines = "1.7.3"
kotlinx-datetime = "0.5.0"
# Hilt
hilt = "2.50"
hilt-compose = "1.1.0"
# AndroidX
androidx-core = "1.12.0"
androidx-appcompat = "1.6.1"
androidx-room = "2.6.1"
androidx-paging = "3.2.1"
androidx-compose = "1.6.1"
androidx-compose-navigation = "2.7.7"
androidx-compose-lifecycle = "2.7.0"
androidx-compose-compiler = "1.5.9"
androidx-compose-material3 = "1.2.0"
androidx-compose-constraintlayout = "1.0.1"
# Network
ktor = "2.3.7"
kotlinx-serialization = "1.6.1"
# UI
coil-compose = "2.4.0"
lottie = "5.2.0"
holix-bottomsheet = "1.3.1"
# Kakao
kakao = "2.12.1"
# Logging
# TODO : Timber 은 Android Library 이니 변경 필요
timber = "5.0.1"
sentry = "7.1.0"
firebase-bom = "32.7.2"
# Debug
leakcanary = "2.12"
okhttp3-logging-interceptor = "4.12.0"
# Common
ted-permission = "3.3.0"

[libraries]
# Kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-compose" }
# AndroidX Presentation
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-compose-navigation" }
androidx-compose-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-compose-lifecycle" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-compose-constraintlayout" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }
# AndroidX Data
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-coroutine = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }
androidx-paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "androidx-paging" }
# Network
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-kotlinx-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
# UI
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
ted-permission = { module = "io.github.ParkSangGwon:tedpermission-coroutine", version.ref = "ted-permission" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
holix-bottomsheet = { module = "com.holix.android:bottomsheetdialog-compose", version.ref = "holix-bottomsheet" }
# Kakao
kakao-user = { module = "com.kakao.sdk:v2-user", version.ref = "kakao" }
# Logging
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
sentry = { module = "io.sentry:sentry-android", version.ref = "sentry" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
# Debug
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3-logging-interceptor" }

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-gradle" }
android-library = { id = "com.android.library", version.ref = "plugin-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
sentry = { id = "io.sentry.android.gradle", version.ref = "plugin-sentry" }
gms = { id = "com.google.gms.google-services", version.ref = "plugin-gms" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "plugin-firebase-crashlytics" }

[bundles]
kotlin = ["kotlin", "kotlinx-coroutines-android", "kotlinx-coroutines-core", "kotlinx-datetime"]
androidx-presentation = ["androidx-core", "androidx-appcompat", "androidx-compose-material3",
    "androidx-compose-navigation", "androidx-compose-constraintlayout",
    "androidx-compose-lifecycle", "holix-bottomsheet", "androidx-paging-compose"]
androidx-data = ["androidx-room-runtime", "androidx-room-coroutine", "androidx-paging-runtime"]
network = ["ktor-core", "ktor-okhttp", "ktor-resources", "ktor-content-negotiation", "ktor-kotlinx-serialization",
    "ktor-auth", "kotlinx-serialization"]
kakao = ["kakao-user"]
logging = ["timber", "sentry", "firebase-analytics", "firebase-crashlytics"]
